name = "catsup-app"
type = "webpack"
account_id = ""
workers_dev = true
compatibility_flags = []
compatibility_date = "2022-02-09"

[dev]
ip = "0.0.0.0"
port = 3000
local_protocol="http"
upstream_protocol="https"

[env.development.vars]
DISCORD_URL = "https://discord.com/api/webhooks/942554263639429131/wFa0nbtOSERf40W6zt0PUgbgFFqiRiiytt2QEJXuWM48WeKtEuqO3QD9ppSg-xz6UFaj"
CLIENT_ID = "Iv1.4470ed4790cf7378"
CLIENT_SECRET = "53df0f8eef820a783432099e25fc35345a6bc311"
WEBHOOK_SECRET = "e81608baf1ddcc6ad8f9b168c477b06712ca7f4d"
APP_ID = 172098
APP_PK = '''
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCybHw6kDCjRzU3
UtbsX7sf1ga6v3QiUodD8pT2l5oISV6SZoTP1lv0jJTMPXGNIbvDt/XbOKZ7zw7R
619y04O7RZtHA5iNnW/hqJ036yS8veUKIYP6Sr9+expnEpYV9IVTYuYQKm1gV4fo
GQp/nC6ZBM/KnUG4RyvWqtsV0feN2h/L9nllETSPWF7wxolkgf1tGNXqoXZuGHIX
KCXhi2Zt0EJQfmHBZRBoH8N6CWWmjGM5by1Dst+hbqxMExEwaLnF/3Cp39SI62Lj
2eR8g/dVrgzKBipDdAKSkL08RfpiyYoyDLbPf8PD3kIQiEo8YezwYC+W/3WvsyPB
6tCV3yeBAgMBAAECggEBAK/S5CC50pQ0KabZBV5tf/MBcCQ7YnAoL4+vz0epYWrl
EkLmr943+OnmVwNlUS6onWVjNO3Qx46eHpaSgb6f3OKA12GFk6GKEaSoCjX+jHdK
EhiHqozNeCNloEEOOcRs762aeehYRux3lUAM3SGfgPPdn/6kNQ0pZXPnbnn0LSUk
taM9dRGmHC1ld037fG0BWOixdjYNszNV6KJnPdG9O7LivqN6/soF2QbiUhhS4qEd
n7C1gbYLHwJk2u2V6kqkudb0sMB931zr1SHEBOuVU5qEE0+G9qN+b3erUrItLW38
VKMkUxzP+d10RNKTZBenlywli54ixmD4IHptbie2gxkCgYEA5IKLYWE+NiKQeCn5
1DcW4jGceFwqAw5kwxH+kceAMEvCFdlBGp52STo9NuPFIkZD2CkCsEaXXes9cGIN
uHpvc+cfiTLeioVWyywEFGt0cNA4CksqKiswCmqYM/FCiY+ZcSAh+YSkoDhcl0F0
ZVU8vafkXNC8UYoEpTVUoQOeW58CgYEAx+Nt7kcu1NZLdlheY6kmbWGT8ogd4FCk
dEwDvNz2iact0uMx8qUNCOIAauoj15qp2N4HfjQVjHS3XnRLy1yrdWhXqAVlStPR
aEuC/LniaTZlsd7NQwEmwldSMxAsS3bMCZCqHDFfFI43oqXR7muQ+ia/Ysk/4XuB
0qFdtooTqN8CgYEA4QmC9CLNHokJl51XENwz6AyNmKbDJQFe0BD/kFdVcbqZ5+Rt
ziYyPUlikZTcRjXGiLFSmYDbfr21YuDdvEivTAhYMUhsiyRnZmzxk56DLLqSBeki
HCcuB4QUYkr9iPVnWlYXv2AWtEbtQHRQiZ7Y07ntFk7mtrJigsSzlGI46OcCgYEA
nr5onHZdo9v4HCl79Kvt/6ohw9gD2hRRNqbzxPa6uIFTbArQrQIVQvuxFzeRdXW3
86oIy1pzzpMW2WWEmCGlbV2LV73JPs7PnINzqF+7hpET3Fm0K8VrUaXlevYaJ2hW
DDaeUjuHZhy35GzKNw2oGnHRRpPLLrhWVr+eXAx2JoMCgYBQlAJKfuJfJnajKTCE
GQR0dvWnRHwZk+751tR8cSvSIpnBXvnW9POJo0vm+ExytBCDc6P89gXOLhM17fRs
NJSaJMJqkB+vsYehlejeqca7gV+bGudxo4Ks45qiUZmlQfl7gssZQdwImlVngsLY
MDLOCUuFGjlre1g/Y71XlT1Kgg==
-----END PRIVATE KEY-----
'''
